@url_dev=http://localhost:5000/api/user
# router.post("/register", createUser);
# router.post("/login", loginUSER);
# router.post("/admin-login", loginADMIN);
# router.post("/administrator-login", loginADMINISTRATOR);
# router.put("/password", authMiddleware, updatePassword);
# router.put("/edit-user", authMiddleware, updatedUser);
# router.put("/reset-password/:token", resetPassword);
# router.put("/511246447/block-user/:id", authMiddleware, hasPermission, blockUser); //admin-put-user
# router.put("/511246447/unblock-user/:id", authMiddleware, hasPermission, unblockUser);
# router.patch("/999457447/update-group/:id", authMiddleware, hasPermission, unblockUser);
# router.get("/refresh", handleRefreshToken);
# router.get("/logout", logout);
# router.get("/all-users", getAllUsers);
# router.get("/511320447/admin/all-users", authMiddleware, hasPermission, getAllUsersWithAdmin);
# router.get("/511320447/info/:id", authMiddleware, hasPermission, getUserWithAdmin);


### register
POST {{url_dev}}/register
Content-Type: application/json
{
    "fullname": "Nguyen Quoc Trang",
    "email": "admin1s@gmail.com",
    "mobile": "0123s34679",
    "password": "apipassword123",
    "address": "TP HCM"
}

### login
POST {{url_dev}}/login
Content-Type: application/json
{
    "email": "usre@gmail.com",
    "password": "apipassword123"
}


### Admin login
POST {{url_dev}}/admin-login
Content-Type: application/json
{
    "email": "usre@gmail.com",
    "password": "apipassword123"
}

### ADMINISTRATOR login
POST {{url_dev}}/administrator-login
Content-Type: application/json
{
    "email": "ADMINISTRATOR@gmail.com",
    "password": "ADMINISTRATOR999"
}


### refresh
GET {{url_dev}}/refresh

### logout
GET {{url_dev}}/logout

### get all user
GET {{url_dev}}/all-users

### get all tickets
GET {{url_dev}}/664c2c2059a44400841cbddb/tickets

### patch update password
PATCH {{url_dev}}/password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2MjhiMDJkNWViNTg3NTQyZTMxNGZiNSIsImlhdCI6MTcxMzk0MzAwMSwiZXhwIjoxNzE0MDI5NDAxfQ.A06tDFuBF78zqKXXMpSXqblxHUiGkKcM1rOWuCiS_N0
{
    "password": "helloword"
}

### update user
PUT {{url_dev}}/edit-user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2MWY4MDljZGQ0MjFmNTkxMmUyZDJlYiIsImlhdCI6MTcxMzM0MDU4NywiZXhwIjoxNzEzNDI2OTg3fQ.YB3K3kpP6IJPihsvyG9VHLCAcw0fPfPI5ZbWHevQHes
Content-Type: application/json
{
    "fullname": "New Fullname",
    "email": "new_email01@example.com",
    "mobile": "01234566009",
    "address": "HN"
}

### update password
PUT {{url_dev}}/password
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2MjhhZGIyYmJiNmEzYWUzNzEyZTBhOSIsImlhdCI6MTcxMzk0MTk1MSwiZXhwIjoxNzE0MDI4MzUxfQ.OVu9-4dq7iKIAp_5RFzgRGwk7FGroVIE6m-O7f5WI1A
Content-Type: application/json
{
    "password": "admin"
}

# ADMIN
### get user
GET {{url_dev}}/511320447/info/6649877d578a6d778d59e17a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NDk4Njk4NTc4YTZkNzc4ZDU5ZTEzZCIsImlhdCI6MTcxNjA5NjcwNCwiZXhwIjoxNzE2MTgzMTA0fQ.4NScp2ucgXWRAlgdtsTMtEUtSYn5pGShckpXpC-FmY4

### get all user
GET {{url_dev}}/511320447/admin/all-users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NDgzOGNjNDE0NjkzODEzYWZlMTY2YSIsImlhdCI6MTcxNjAwOTE4NywiZXhwIjoxNzE2MDk1NTg3fQ.I9lBaGhcdi2RuWAHmBf38F-V_xoxmtlJYfMvAv8ArhY

### put block user
PUT {{url_dev}}/511246447/block-user/664838f6414693813afe167c
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NDgzOGNjNDE0NjkzODEzYWZlMTY2YSIsImlhdCI6MTcxNjAwOTE4NywiZXhwIjoxNzE2MDk1NTg3fQ.I9lBaGhcdi2RuWAHmBf38F-V_xoxmtlJYfMvAv8ArhY

### unblock user
PUT {{url_dev}}/511246447/unblock-user/664838f6414693813afe167c
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NDgzOGNjNDE0NjkzODEzYWZlMTY2YSIsImlhdCI6MTcxNjAwOTE4NywiZXhwIjoxNzE2MDk1NTg3fQ.I9lBaGhcdi2RuWAHmBf38F-V_xoxmtlJYfMvAv8ArhY

### update group user
PATCH {{url_dev}}/999457447/update-group/664c06442aba1491b9b4bbba
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NGMwNjNkMmFiYTE0OTFiOWI0YmJhYyIsImlhdCI6MTcxNjI1ODQwNiwiZXhwIjoxNzE2MzQ0ODA2fQ.0JEhT1sKNx6fDaoJdsIfaduZQbrz1RDAwlsqCmrkenY
Content-Type: application/json
{
    "group_id": "664c06832aba1491b9b4bbc3"
}