@url_dev=http://localhost:5000/api/user

### register
POST {{url_dev}}/register
Content-Type: application/json
{
    "fullname": "Nguyen Quoc Trang",
    "email": "user@gmail.com",
    "mobile": "0123456789",
    "password": "apipassword123",
    "address": "TP HCM"
}

### login
POST {{url_dev}}/login
Content-Type: application/json
{
    "email": "user@gmail.com",
    "password": "apipassword123"
}


### Admin login
POST {{url_dev}}/admin-login
Content-Type: application/json
{
    "email": "admin@gmail.com",
    "password": "admin"
}


### refresh
GET {{url_dev}}/refresh

### logout
GET {{url_dev}}/logout

### get all user
GET {{url_dev}}/all-users

### put reset password
PUT {{url_dev}}/reset-password/d4a68ec86a19ef9a597e861535923df84afd8c57f5d7ffe11c84950d8a290c8e
Content-Type: application/json
{
    "password": "helloword"
}

### update user
PUT {{url_dev}}/edit-user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2MWY4MDljZGQ0MjFmNTkxMmUyZDJlYiIsImlhdCI6MTcxMzM0MDU4NywiZXhwIjoxNzEzNDI2OTg3fQ.YB3K3kpP6IJPihsvyG9VHLCAcw0fPfPI5ZbWHevQHes
Content-Type: application/json
{
    "fullname": "New Fullname",
    "email": "new_email01@example.com",
    "mobile": "01234566009",
    "address": "HN"
}

### update password
PUT {{url_dev}}/password
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2MWY4MmRjODE0MWQyMjAzZDE4MDNiMCIsImlhdCI6MTcxMzM0MTc4OCwiZXhwIjoxNzEzNDI4MTg4fQ.LRbAeM6wivAZM9wEuAL1LwpnHA7KNIUR_QjiccrqAGw
Content-Type: application/json
{
    "password": "admin"
}

