@url_dev=http://localhost:5000/api/flight

### Tạo một chuyến bay mới
POST {{url_dev}}/511454641/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2MzY0OWZiNjc2ODViOWIwNGFjYjY0ZSIsImlhdCI6MTcxNDgzMzk2NiwiZXhwIjoxNzE0OTIwMzY2fQ.9srC2zSiON5ftn5AJAFe_MKUOwz4n5Ue7TbcXQ64TTw
{
    "flight_number": "MH370-BOEING777777",
    "flight_code": "HAN-SGNNNN",
    "departure_airport": "66364a9367685b9b04acb66e",
    "destination_airport": "66364da2083d44d27ecaad97",
    "departure_datetime": "2024-04-20T08:00:00.000Z",
    "duration": 30,
    "ticket_price": 1000,
    "seats": [
        {"class": "1", "count": 20, "booked_seats": 0, "status": true},
        {"class": "2", "count": 80, "booked_seats": 0, "status": true}
    ],
    "transit_airports": [
        {"airport_id": "66364a9367685b9b04acb66e", "stop_duration": 10, "note": ""},
        {"airport_id": "66364a9d67685b9b04acb675", "stop_duration": 15, "note": "delay 2 minutes"}
    ],
    "rules": {
        "regulation_1": {
            "flight_time": "663649fb67685b9b04acb651",
            "intermediate": "663649fb67685b9b04acb652"
        },
        "regulation_2": {
            "tickets": "663649fb67685b9b04acb653"
        },
        "regulation_3": {
            "booking": "663649fb67685b9b04acb654"
        }
    }
}



### Lấy tất cả các chuyến bay
GET {{url_dev}}/all

### Lấy thông tin của một chuyến bay dựa trên ID
GET {{url_dev}}/{{flight_id_here}}

### Cập nhật thông tin của một chuyến bay dựa trên ID
PUT {{url_dev}}/6620126f269aaa629bfd19fc
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2MWY4MmRjODE0MWQyMjAzZDE4MDNiMCIsImlhdCI6MTcxMzM1MzgyMSwiZXhwIjoxNzEzNDQwMjIxfQ.Wj-benP-bbrUNoWxN-SXW0ihREkTX0yYOPLxDcd26JE
{
    "departureTime": "2024-04-21T08:00:00.000Y",
    "transit_airports": [
        {"airport_id": "6620020b3b74f1bf677edb0f", "stop_duration": 5, "rule_id": "662016cac5c298bf41797795"},
        {"airport_id": "662002523b74f1bf677edb1d", "stop_duration": 20, "rule_id": "662000b0733c072ad08dc5e0"}
    ]
}

### Cập nhật thông tin ghế ngồi của một chuyến bay dựa trên ID
PUT {{url_dev}}/6621dfe08fbf71902dbed73d/seats/6621dfe08fbf71902dbed73e
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2MWY4MmRjODE0MWQyMjAzZDE4MDNiMCIsImlhdCI6MTcxMzQ5NTIxNiwiZXhwIjoxNzEzNTgxNjE2fQ.VbJeqISlEBqABYHLw5Q2DCM49kG4UaQ1Sv5R1cLjmOs
{
    "count": 20
}


### Xóa một chuyến bay dựa trên ID
DELETE {{url_dev}}/6620a46c47a97d2cb55b7aee
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2MWY4MmRjODE0MWQyMjAzZDE4MDNiMCIsImlhdCI6MTcxMzM1MzgyMSwiZXhwIjoxNzEzNDQwMjIxfQ.Wj-benP-bbrUNoWxN-SXW0ihREkTX0yYOPLxDcd26JE
