@url_dev=http://localhost:5000/api/flight

### Tạo một chuyến bay mới
POST {{url_dev}}
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2MWY4MmRjODE0MWQyMjAzZDE4MDNiMCIsImlhdCI6MTcxMzM1MzgyMSwiZXhwIjoxNzEzNDQwMjIxfQ.Wj-benP-bbrUNoWxN-SXW0ihREkTX0yYOPLxDcd26JE

{
    "flight_code": "ABC123",
    "departure_airport": "Hanoi",
    "destination_airport": "Ho Chi Minh City",
    "departure_datetime": "2024-04-20T08:00:00.000Z",
    "duration": 120,
    "ticket_price": 1000,
    "seats": 150,
    "transit_airports": [
        {"name": "Danang", "stop_duration": 15},
        {"name": "Nha Trang", "stop_duration": 10}
    ]
}


### Lấy tất cả các chuyến bay
GET {{url_dev}}

### Lấy thông tin của một chuyến bay dựa trên ID
GET {{url_dev}}/{{flight_id_here}}

### Cập nhật thông tin của một chuyến bay dựa trên ID
PUT {{url_dev}}/{{flight_id_here}}
Content-Type: application/json
Authorization: Bearer your_access_token_here

{
    "departureTime": "2024-04-21T08:00:00.000Z",
    "duration": 150
}

### Xóa một chuyến bay dựa trên ID
DELETE {{url_dev}}/{{flight_id_here}}
Authorization: Bearer your_access_token_here
