@url_dev=http://localhost:5000/api/group
# router.post("/511454413/create", authMiddleware, hasPermission, createGroup);
# router.get("/511320413/all", authMiddleware, hasPermission, getAllGroups);
# router.get("/511320413/:id", authMiddleware, hasPermission, getGroup);
# router.put("/511246413/update/:id", authMiddleware, hasPermission, updateGroup);
# router.delete("/511627413/delete/:id", authMiddleware, hasPermission, deleteGroup);

### get all
GET {{url_dev}}/511320413/all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2MjkxMjU5ZTM3ZDhhYjQxZjVmYWYwNiIsImlhdCI6MTcxMzk2ODExMCwiZXhwIjoxNzE0MDU0NTEwfQ.TMxh4gZ0dO6_BaWjIvFG5MogYo8JsMmvEN3X5apQ024

### get by id
GET {{url_dev}}/511320413/6628cdac982323272d5c0163
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2MjhjZGFjOTgyMzIzMjcyZDVjMDFjZCIsImlhdCI6MTcxMzk1MDk2MiwiZXhwIjoxNzE0MDM3MzYyfQ.ph_5wLtIKbL40nBUYMjetW-Q5rBJqyF7EBbeLpi6Gd4

### update by id
PUT {{url_dev}}/511246413/update/6628cdac982323272d5c0162
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2MjhjZGFjOTgyMzIzMjcyZDVjMDFjZCIsImlhdCI6MTcxMzk1MDk2MiwiZXhwIjoxNzE0MDM3MzYyfQ.ph_5wLtIKbL40nBUYMjetW-Q5rBJqyF7EBbeLpi6Gd4
Content-Type: application/json
{
    "groupCode": "511"
}

### create group
POST {{url_dev}}/511454413/create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2MjkxMjU5ZTM3ZDhhYjQxZjVmYWYwNiIsImlhdCI6MTcxMzk2ODExMCwiZXhwIjoxNzE0MDU0NTEwfQ.TMxh4gZ0dO6_BaWjIvFG5MogYo8JsMmvEN3X5apQ024
Content-Type: application/json
{
    "groupCode": "001",
    "groupName": "Write"
}