@url_dev=http://localhost:5000/api/permission
# router.post("/511454990/create", authMiddleware, hasPermission, createPermission);
# router.get("/511320990/all", authMiddleware, hasPermission, getAllPermissions);
# router.get("/511320990/:id", authMiddleware, hasPermission, getPermission);
# router.put("/511246990/update/:id", authMiddleware, hasPermission, updatePermission);
# router.delete("/511627990/delete/:id", authMiddleware, hasPermission, deletePermission);
### Create
POST {{url_dev}}/511454990/create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NGMwNjNkMmFiYTE0OTFiOWI0YmJhYyIsImlhdCI6MTcxNjI1ODQwNiwiZXhwIjoxNzE2MzQ0ODA2fQ.0JEhT1sKNx6fDaoJdsIfaduZQbrz1RDAwlsqCmrkenY
Content-Type: application/json
{
    "group_id": "664c06832aba1491b9b4bbc3", 
    "functionality_ids": [
        "664c063d2aba1491b9b4bab0"
        "664c063d2aba1491b9b4ba9e",
        "664c063d2aba1491b9b4baa0",
        "664c063d2aba1491b9b4baa2",
        "664c063d2aba1491b9b4baa4"
    ]
}

### Get all permissions
GET {{url_dev}}/511320990/all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2MjkxMjU5ZTM3ZDhhYjQxZjVmYWYwNiIsImlhdCI6MTcxMzk2ODExMCwiZXhwIjoxNzE0MDU0NTEwfQ.TMxh4gZ0dO6_BaWjIvFG5MogYo8JsMmvEN3X5apQ024

### Get all permissions by userID
GET {{url_dev}}/511000000/664c345073c4df2df3e6a0ad/all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NGMwYjk4MGMxZmNiMzVlYTZkZjQ5OCIsImlhdCI6MTcxNjI3MDExNiwiZXhwIjoxNzE2MzU2NTE2fQ.fPD3Jtzuha029XbnlhwjU9L4j6X_hUqDy3shfhnejEI
### Get a single permission
GET {{url_dev}}/511320990/6628a0640f03a5640fd6f68d
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2MjhhMDY0MGYwM2E1NjQwZmQ2ZjZkZSIsImlhdCI6MTcxMzkzOTg3MCwiZXhwIjoxNzE0MDI2MjcwfQ.0lfIxsFIUF8U3b6S3oLgvyFFdfzwkY8cXJ_Xb4Np00w

### Update a permission
PUT {{url_dev}}/511246990/update/66291482e37d8ab41f5faf38
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2MjkxMjU5ZTM3ZDhhYjQxZjVmYWYwNiIsImlhdCI6MTcxMzk2ODExMCwiZXhwIjoxNzE0MDU0NTEwfQ.TMxh4gZ0dO6_BaWjIvFG5MogYo8JsMmvEN3X5apQ024
Content-Type: application/json
{
    "group_id": "6629140ce37d8ab41f5faf2d",
    "functionality_id": "66291259e37d8ab41f5fae66"
}

### Delete a permission
DELETE {{url_dev}}/511627990/delete/6628a0640f03a5640fd6f68d
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2MjhhMDY0MGYwM2E1NjQwZmQ2ZjZkZSIsImlhdCI6MTcxMzkzOTg3MCwiZXhwIjoxNzE0MDI2MjcwfQ.0lfIxsFIUF8U3b6S3oLgvyFFdfzwkY8cXJ_Xb4Np00w
