@url_dev=http://localhost:5000/api/request-reservations

###
POST {{url_dev}}/booking
Content-Type: application/json
{
    "user_id" : "664838f6414693813afe167c",
    "flight_id" : "66483a7c414693813afe16b9",
    "seat_class" : "1",
    "full_name" : "Nguyen Van A",
    "CMND" : "6123179891287",
    "phone_number" : "0907722321"
}
###
GET {{url_dev}}/request/6648293c081020c4f73870bb

###
GET {{url_dev}}/580320946/request-all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NDgzOGNjNDE0NjkzODEzYWZlMTY2YSIsImlhdCI6MTcxNjAwOTE4NywiZXhwIjoxNzE2MDk1NTg3fQ.I9lBaGhcdi2RuWAHmBf38F-V_xoxmtlJYfMvAv8ArhY
###
PATCH {{url_dev}}/580457946/66483b04ff57dbd6ac304c7a/success
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NDgzOGNjNDE0NjkzODEzYWZlMTY2YSIsImlhdCI6MTcxNjAwOTE4NywiZXhwIjoxNzE2MDk1NTg3fQ.I9lBaGhcdi2RuWAHmBf38F-V_xoxmtlJYfMvAv8ArhY